# Generated by Django 5.0 on 2023-12-04 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Stars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1, verbose_name='Звезда')),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('work_time', models.CharField(max_length=150, verbose_name='Время работы')),
                ('phone_num', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('description', models.TextField(verbose_name='Описание')),
                ('map_link', models.TextField(verbose_name='Ссылка на карту')),
                ('picture', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Изображение')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='offers.city', verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Контент')),
                ('id_offer', models.CharField(max_length=150, verbose_name='ID предложения')),
                ('stars', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='offers.stars', verbose_name='Звезда')),
            ],
        ),
    ]
